### PR TITLE
Support UIKit completions

### PR DESCRIPTION
**Pull request by ThangaAyyanar**
UIkit completions support #6

### CODE REVIEW

**Comment by ThangaAyyanar** [comment]
final code for target Architecture will be
```
  let targetArch = config.targetArch
  if (targetArch) {
      args = args.concat(['-Xswiftc', '-target', '-Xswiftc', targetArch])
  }else{
      args = args.concat(['-Xswiftc', '-target', '-Xswiftc', 'x86_64-apple-ios13.2-simulator'])
  }
```
is it okay to have 'x86_64-apple-ios13.2-simulator' as default?, your suggestion on this @klaaspieter

**Comment by klaaspieter** [comment]
@ThangaAyyanar sorry I was out on vacation. I think I would prefer no default for this since it's a moving target (it can change with every new iOS release).

Also can you add the new configuration key to the README https://github.com/klaaspieter/coc-sourcekit#configuration-options?

**Comment by ThangaAyyanar** [comment]
Sure i will do it

**Comment by ThangaAyyanar** [comment]
Done

**Comment by klaaspieter** [comment]
Thank you 🙏

**Comment by WhyNotHugo** [comment]
Hi! The default doesn't work for me, but I've no idea why.

```
$ xcrun --sdk iphonesimulator --show-sdk-path
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'iphonesimulator'
```

The SDK seems to be there: `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk`.

However, even setting the right sdk explicily, I still get errors like:

    [sourcekitd] [E] cannot find 'UIPasteboard' in scope ...

Any hints here?

**Pull request merged**
