### PR TITLE
Add Support for Environment Variables

### PR DESCRIPTION
**Pull request by LebJe**
Hi @klaaspieter!

This pull request adds support for passing environment variables to sourcekit-lsp.

Jeff

### CODE REVIEW

**Comment by keith** [comment]
What's the use case for this?

**Comment by LebJe** [comment]
@keith I'm currently using it to set the `SOURCEKIT_TOOLCHAIN_PATH` to the directory the Swift toolchain is in.

```json
"sourcekit.env": { 
    "SOURCEKIT_TOOLCHAIN_PATH": "/home/USER/swift-DEVELOPMENT-SNAPSHOT-2021-07-30-a-ubuntu20.04/" 
}
```

**Comment by keith** [comment]
Nice! Maybe worth adding that example in the description for folks?

**Comment by klaaspieter** [comment]
@LebJe I agree with @keith. Do you mind adding this to the README with an example?

**Comment by klaaspieter** [comment]
Thank you 🙏🏻

**Pull request merged**
